### ISSUE TITLE
Provide spec in non-proprietary format

### ISSUE THREAD

**Issue by ghost** [oasis-open/cti-documentation#17]
The page https://oasis-open.github.io/cti-documentation/ says:

> [Read the Latest Specification! (2.0 CSD 1)](https://docs.google.com/document/d/1yvqWaPPnPW-2NiVCLqzRszcx91ffMowfT5MmE9Nsy_w)

Unfortunately, the link goes to a [Google Doc](https://en.wikipedia.org/wiki/Google_Docs,_Sheets_and_Slides), which is not readable without the user executing (and trusting) proprietary JavaScript. This makes the specification inaccessible to users who are, due to security requirements or resource constraints, etc, unwilling or unable to do that.

As the rest of the site seems to be being collaboratively edited here on GitHub, the use of Google Docs seems anomalous and unnecessary, especially given that the spec is the most important document on the site. Please can the spec instead be stored using a lightweight markup language, such as one of the ones [supported by GitHub](https://github.com/github/markup#markups), and published as HTML?

(N.B. All of those lightweight markup languages can be exported to PDF or ODT, etc, if necessary for print publication or suchlike, using [Pandoc](https://en.wikipedia.org/wiki/Pandoc) or other tools.)

**Comment by johnwunder** [comment]
The CTI technical committee (which developers the specification) has, for now, chosen to use Google Docs to do our specification development and editing because it provides the collaborative editing features that let us all get on a call and edit the document live.

We do recognize that people might not want to go to Google Docs to review the specification or, certainly, to read it once it's finished. Once the specification is published (it's currently under ballot) it will be published in raw HTML, PDF, and .docx on oasis-open.org and that link will be updated. In the meantime, you can also access a .docx instance here: https://www.oasis-open.org/committees/download.php/61074/stix-v2.0-wd03.zip.

I'll leave this issue open until we're able to link to the HTML.

**Comment by ghost** [comment]
@johnwunder wrote:
> We do recognize that people might not want to go to Google Docs to review the specification or, certainly, to read it once it's finished. Once the specification is published (it's currently under ballot) it will be published in raw HTML, PDF, and .docx on oasis-open.org and that link will be updated. In the meantime, you can also access a .docx instance here: https://www.oasis-open.org/committees/download.php/61074/stix-v2.0-wd03.zip.

For people who want to review the spec before it is finalised, a better option would be if you could:

* use Google Docs's ["publish" feature](https://support.google.com/docs/answer/37579?hl=en) to provide an automatically-updated HTML rendering of the document, and;
* provide a link to that rendering's URL (e.g. with link text "View as HTML") alongside the link mentioned in my opening comment above.

> I'll leave this issue open until we're able to link to the HTML.

:thumbsup:

**Comment by gtback** [comment]
@sampablokuper Very cool! I didn't know about that feature in Google Docs. It's good to see that changes made in the document are automatically updated in the published version (unless you explicitly turn off the updating). 

There is some minimal JavaScript on the resulting page, but disabling it does not appear to affect the rendered content.

**Comment by ghost** [comment]
@gtback thanks. Glad it is working for you.

Any chance you could edit your [index.md](https://github.com/oasis-open/cti-documentation/blob/master/index.md) to add links to the Google Docs-generated HTML versions of both the STIX and TAXI specs, so that others are also able to benefit?

**Comment by johnwunder** [comment]
Yeah that's a great idea. @gtback @ATweedMITRE here are the links, can you get them posted? We may need some kind of landing page or new call-out box on the homepage to point to all 5? Not sure of the best way of doing that.

Part 5: https://docs.google.com/document/d/1nK1RXcE2aMvQoG1Kgr3aTBtHZ1IyehzOk7vU0n5FUGY/pub
Part 4: https://docs.google.com/document/d/167aIyr5BIAJJORzjT11U25cGSBJ0cBNSdkheNJFz6l8/pub
Part 3: https://docs.google.com/document/d/1ti4Ei_ii_Uc4izHNZlYmBP9NgD5-iVWC--y-3HmGZyg/pub
Part 2: https://docs.google.com/document/d/1IvkLxg_tCnICsatu2lyxKmWmh1gY2h8HUNssKIE-UIA/pub
Part 1: https://docs.google.com/document/d/1dIrh1Lp3KAjEMm8o2VzAmuV0Peu-jt9aAh1IHrjAroM/pub

**Comment by clenk** [comment]
This was addressed in 7852ada.

**Comment by ghost** [comment]
@clenk wrote:
> This was addressed in 7852ada.

Thanks! Any chance you could do something similar for the TAXII spec as well? (I.e. in the other column on [this page](https://oasis-open.github.io/cti-documentation/).)

**Comment by gtback** [comment]
@johnwunder can you "publish" the TAXII spec? I don't have permissions on that document

**Comment by gtback** [comment]
This is the TAXII spec: https://docs.google.com/document/d/1Jv9ICjUNZrOnwUXtenB1QcnBLO35RnjQcJLsa1mGSkI/pub

**Comment by clenk** [comment]
This was addressed for the TAXII spec in 73c0fa5.

**Comment by gtback** [comment]
@sampablokuper , I think this is done, but let us know if we missed anything. Thanks!
