### ISSUE TITLE
Create STIX Overview/Getting Started Guide for STIX 2.0

### ISSUE THREAD

**Issue by ATweedMITRE** [oasis-open/cti-documentation#20]

**Comment by SecurityDozo** [comment]
Isn't this already addressed through the About/Walkthrough pages?

**Comment by ATweedMITRE** [comment]
I think generally the About/Walkthrough pages provide information about what STIX is and how one could use it but doesn't give a detailed overview/starter guide for how a new user would get started in actually using STIX.

**Comment by SecurityDozo** [comment]
Ahh ok, I see the difference. Point them directly to the packages with usage examples, kinda like the  Examples and Tutorials page but more simple.

**Comment by ATweedMITRE** [comment]
Now up on the site [here](https://oasis-open.github.io/cti-documentation/stix/gettingstarted).
