### ISSUE TITLE
Labeling/Tagging system for examples

### ISSUE THREAD

**Issue by Bojak4616** [oasis-open/cti-documentation#28]
Label each example, which is currently being done with STIX icons, with a tag of what the example describes. The list should be filterable so that a user that only needs help with one or two STIX objects can access them quickly. 

Something [like this](https://www.w3schools.com/jsref/jsref_filter.asp) where `age` is sanitized user input for what STIX objects they want to see.

**Comment by gtback** [comment]
We did something similar on the old stixproject.github.io site. See https://stixproject.github.io/documentation/idioms/

**Comment by SecurityDozo** [comment]
Perfect! Since there is already existing code I could get this moved done sooner rather than later.

**Comment by gtback** [comment]
I made a few comments on 0957ccb584b7ab1553392a7b37e73adf372ef840 asking for a couple tweaks.

**Comment by SecurityDozo** [comment]
@gtback Tweaks have been made in #34 . I chose to highlight the current filter being used in the list .

**Comment by gtback** [comment]
Closed by #32 and #34
