### ISSUE TITLE
Bunch of low priority fixes suggested by a UX Reviewer

### ISSUE THREAD

**Issue by Bojak4616** [oasis-open/cti-documentation#35]
### Suggestions

Num | Page | Description   of Issue | Recommendation
-- | -- | -- | --
1 | Specifications Document | It is a little challenging to navigate the   Specifications document because it primarily uses a Table of Contents with   page numbers to navigate the document.    Page numbers are meaningless when reading a document on the web.  Plus, if you jump further down in the   document, there is no easy way to return to the top without a lot of   scrolling. | It may not be possible in Google Docs, but it would   be great to use in-page links to jump to the sections and return using Back   to Top.  This page contains usability   guidance on the use of  [Back to Top links](https://www.nngroup.com/articles/back-to-top/).
2 | FAQ | The FAQ page and document is slightly overwhelming because of how   comprehensive it is. | Suggest listing a top 10 questions on the FAQ page with a link to download   the full FAQ.
3 | STIX Examples | STIX Type icons don’t have tool tips that display the labels. | Add tool tips to the STIX Type icons.
4 | TAXII 1.x website | The most prominent link on the page is to get   started with TAXII 1.x.  The link to go   to the TAXII 2.0 website is much less noticeable. | Make the link to go to TAXII 2.0 the most noticeable   if you want to migrate people to 2.0.

**Comment by SecurityDozo** [comment]
### General Comments 

1. Solve by linking to both versions in Google Docs. (The currently used pub version and the javascript version)

2. John Wonder is still pushing for this - It's in the pipeline

**Comment by SecurityDozo** [comment]
Fixed in PR #36
