### ISSUE TITLE
Add Interoperability from CTI-Cover page to Resources page

### ISSUE THREAD

**Issue by Bojak4616** [oasis-open/cti-documentation#39]
Title

**Comment by SecurityDozo** [comment]
Only Part 1 was added, since it passed peer review. Part 1 still needs to be made public like the other specification documents so it can a text version can be linked.

Part 2 is still under review and thus not added to the site.

**Comment by SecurityDozo** [comment]
Added Part 1 published document in ac2e7996f33902bf615e660b515ac675d36b3cce

**Comment by ejratl** [comment]
STIX 2.1 and TAXII Interoperability Test Document Version 1.0 have now been published and need to be added to the resources page.
