### ISSUE TITLE
FAQ Page needs reworking

### ISSUE THREAD

**Issue by Bojak4616** [oasis-open/cti-documentation#44]
The current state of the FAQ page is a temporary fix. Until the FAQ is approved by the TC I cannot add direct questions onto the website. Once this takes place, the most important questions should be listed on the website with a link to the complete FAQ hosted in Google Docs.

**Comment by ejratl** [comment]
FAQ has been reworked. It may still require a bit of updating, but PR #86 fixes this issue.

**Comment by ejratl** [comment]
The new FAQ syntax worked locally, but not on the site, so the FAQ needs to be reworked again.

**Comment by sparrell** [comment]
You might need to add a markdown processor to your Jekyll config. See https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/setting-a-markdown-processor-for-your-github-pages-site-using-jekyll
