### ISSUE TITLE
Update Resources Links to published specs

### ISSUE THREAD

**Issue by gtback** [oasis-open/cti-documentation#47]
https://oasis-open.github.io/cti-documentation/resources.html

Should point to files under https://docs.oasis-open.org/cti/stix/v2.0/ and https://docs.oasis-open.org/cti/taxii/v2.0/ (at a minimum the HTML versions, probably the PDFs as well, and possibly the DOCX versions). 

I would get rid of the links to individual parts' Google Docs, and move the link to the Cover Page and Road Map to under the Spec links. Interop can still link to Google Docs, since as far as I know there's no version published on docs.oasis-open.org.

**Comment by gtback** [comment]
Could also just link to https://www.oasis-open.org/standards#stix2.0 and https://www.oasis-open.org/standards#taxii2.0

**Comment by clenk** [comment]
This has been completed. Future versions of the specs should have new issues opened for adding links to them.
