### ISSUE TITLE
Git Hooks Documentation

### ISSUE THREAD

**Issue by clenk** [oasis-open/cti-documentation#48]
While https://oasis-open.github.io/cti-documentation/hooks/ is helpful information, its audience seems to be editors/developers of this documentation, not readers of it. I suggest at least that that page not be a link in the top-level navbar menu, and perhaps not included in the website output at all.

**Comment by SecurityDozo** [comment]
I didn't even notice that. Hadn't thought that it would automatically propagate to the actual website. Will fix ASAP

**Comment by SecurityDozo** [comment]
What's weird is that when I build/serve the site locally, the GitHooks folder is not in the navbar. This makes troubleshooting interesting.

**Comment by SecurityDozo** [comment]
Fixed in 8ca50fd217b99752bb4afa5388721545956ac3ab. Thanks for catching this @clenk :)
