### ISSUE TITLE
Update documentation and examples for STIX/TAXII 2.1

### ISSUE THREAD

**Issue by djhaynes** [oasis-open/cti-documentation#54]
We need to update the STIX/TAXII documentation and examples to align with STIX 2.1 and TAXII 2.1.

**Comment by rpiazza** [comment]
@djhaynes,

Can you list a few places where we need to do this?  Are you thinking of read the docs?

**Comment by djhaynes** [comment]
@rpiazza here are a few places. There are probably more.

- STIX examples (https://oasis-open.github.io/cti-documentation/stix/examples). I tried to validate a couple objects and they failed. 

- List of STIX objects and Objects Overview video (https://oasis-open.github.io/cti-documentation/stix/intro)

- More STIX examples (https://oasis-open.github.io/cti-documentation/stix/compare)

- Links to specifications (https://oasis-open.github.io/cti-documentation/resources and https://oasis-open.github.io/cti-documentation/resources.html#taxii-20-specification)

**Comment by rpiazza** [comment]
Good catch - I hadn't realized that we had copied that documentation over to oasis-open...

**Comment by clenk** [comment]
Fixed by #60.
