### ISSUE TITLE
Inconsistent documentation of properties in Indicator and Malware analysis SDO

### ISSUE THREAD

**Issue by jullle3** [oasis-open/cti-documentation#69]
Hi, these are minor but confusing issues in the STIX 2.1 specification.

In The STIX 2.1 specification, i've found the following inconsistencies:
Under 4.6 (Indicator), Indicator specific properties are missing the following properties:
'pattern_type', 'pattern_version'. Both of these properties show up in the table on 4.6.1

Under 4.11 (Malware analysis) in Malware Analysis specific properties it shows 'installed_software_ref', but in the table on the next side, it shows the property as 'installed_software_refs'. I assume the one ending in 'refs' is the correct? The same goes for 'module' showing up as 'modules' on the next page.

**Comment by rpiazza** [comment]
@jullle3,

Nice catch!  I have put in an issue for us to fix this in the spec.
https://github.com/oasis-tcs/cti-stix2/issues/241
